name: quantbit_crm
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  dio: ^4.0.6
  fluttertoast: ^8.1.2
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  another_flushbar: ^1.12.29
  flutter_speed_dial:
  flutter_native_contact_picker: ^0.0.3
  table_calendar:
  toggle_switch: ^2.0.1
  easy_dynamic_theme: ^2.2.0
  interval_time_picker: ^2.0.0+5
  google_fonts: ^2.3.1
  intl: ^0.17.0
  date_picker_timeline: ^1.2.3
  syncfusion_flutter_datepicker: ^19.4.56
  flushbar: ^1.10.4
  splashscreen: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
     - assets/

