name: quantbit_crm
description: Quantbit CRM Flutter App project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  flutter_speed_dial:
  flutter_native_contact_picker: ^0.0.3
  google_fonts: ^2.3.1
  intl: ^0.17.0
  date_picker_timeline: ^1.2.3
  table_calendar: 
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  google_maps_flutter: ^2.2.3
  url_launcher: ^6.1.8
  get_it: ^7.2.0
  tflite_flutter: ^0.9.0
  camera: ^0.9.4+19
  path: ^1.8.0
  google_ml_kit: ^0.5.0
  image: ^3.0.2
  sqflite: ^2.0.2
  auto_reload: ^1.1.0
  call_log: ^4.0.0
  workmanager: ^0.5.1
  json_annotation: ^4.8.0
  location: ^4.4.0
  syncfusion_flutter_calendar: ^20.4.52

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
     - assets/

